backend:
  name: github
  branch: master
  repo: Mhmdrza/netlify-data-test

media_folder: static/img
public_folder: /img

collections:
  - name: "a2"
    label: aa2
    folder: "src/pages/a"
    create: true
    fields:
      - name: aa
        widget: string
  - name: "product"
    label: "product"
    folder: "src/content/products"
    create: true
    fields:
      - label: "slide1 intro image"
        name: "slide1_image"
        widget: "image"
      - name: "slide2"
        widget: object
        fields:
          - name: "headers"
            widget: object
            fields:
              - name: "header1"
                widget: string
              - name: "subHeader1"
                widget: string
          - name: "paragraph"
            widget: string
      - name: slide3
        widget: object
        fields:
          - name: header
            widget: string
          - name: cards
            widget: list
            fields:
              - name: cardHeading
                widget: string
              - name: cardText
                widget: string
              - name: icon
                widget: string
                description: font awesome icon (e.g. fa-spin)
              - name: url
                widget: string
